# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx1024m
      MAVEN_VERSION: 3.5.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:b8:4a:86:da:b3:7f:35:f5:62:68:61:d6:29:8b:ac"
      - checkout
      - restore_cache:
           key: spring-data-aerospike-{{ checksum "pom.xml" }}
      - run:
          name: Setup maven ${MAVEN_VERSION}
          command: |
                sudo wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
                sudo tar -xvzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt/
      - run: /opt/apache-maven-${MAVEN_VERSION}/bin/mvn dependency:go-offline # gets the project dependencies
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: spring-data-aerospike-{{ checksum "pom.xml" }}

      - run:
          name: Run build with tests
          command:  if [[ -z "$GIT_USER_EMAIL" ]]; then  /opt/apache-maven-${MAVEN_VERSION}/bin/mvn clean install -Dgpg.skip  -U --batch-mode -Dmaven.test.redirectTestOutputToFile=true;fi
      - run:
           name: Save test results
           command: |
                  mkdir -p ~/junit/
                  find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
                  bash <(curl -s https://codecov.io/bash)
           when: always
      - store_test_results:
            path: ~/junit
      - store_artifacts:
            path: ~/junit
      - run:
            name: Save artifacts
            command: |
                    mkdir -p ~/artifacts/
                    find . -type f -regex ".*/target/.*jar" -exec cp {} ~/artifacts/ \;
            when: always
      - store_test_results:
            path: ~/artifacts
      - store_artifacts:
            path: ~/artifacts